[package]
name = "sunrise"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

[dependencies]
egg-mode = "0.10.0"
hyper = "0.11.0"
futures = "0.1.0"
hyper-tls = "0.1.2"
tokio-core = "0.1.0"
regex = "0.2.1"
chrono = "0.4.0"
serde = "1.0.0"
toml = "0.4.0"
slog = "2.0.5"
slog-term = "2.0.1"
clap = "2.24.2"
serde_json = "1.0.2"
